config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check
  #display all task
  get 'tasks', to: 'tasks#index'
  # get new task form
  get 'tasks/new', to: 'tasks#new', as: :new_task
  # display a single task
  get 'tasks/:id', to: 'tasks#show', as: :task
  # create a new task
  post '/tasks', to: 'tasks#create'
  # get the edit form
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # update task
  patch 'tasks/:id', to: 'tasks#update'
  # delete task
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    set_task
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to tasks_url
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_url(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_url
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/taks.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "tasks", "data-turbo-track": "reload" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="form">
  <%= form_for task do |f| %>
    <div class="field mb-3 col-3">
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title, class: "form-control", placeholder: 'title'%>
    </div>

    <div class="field mb-3 col-6">
      <%= f.label :details, class: "form-label" %>
      <%= f.text_area :details, rows: 4, class: "form-control", placeholder: 'details' %>
    </div>
    <%= f.submit "Save", class: "btn btn-primary col-2"%>
    <%= link_to "Back to list", tasks_url, class: "btn btn-danger back-link"%>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="new-task">
  <h1>Edit Task</h1>
</div>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="tasks-box form-check">
  <h1>My Tasks</h1>
  <hr class="col-4">
  <form action="" class="tasks" method="">
    <%@tasks.each do |task|%>
      <label for="tasks<%=task.id%>" class="form-check-label">
        <input type="checkbox" name="tasks<%=task.id%>" id="<%=task.id%>" value="Task<%=task.id%>" class="form-check-input">
        <%=link_to task.title.capitalize, task_url(task), class: 'task-link'%>
        <%=link_to 'delete', delete_url(task), data: { turbo_method: :delete, turbo_confirm: 'are you sure?' }, class: 'delete-btn btn btn-danger'%>
      </label>
      <br>
    <%end%>
  </form>
  <hr class="col-4">
  <%=link_to 'add', new_task_url, class: 'task-link btn btn-primary col-2'%>
</div>

app/views/tasks/new.html.erb
<div class="new-task">
  <h1>New Task</h1>
  <%= render 'form', task: @task%>
</div>

app/views/tasks/show.html.erb
<div class="task-panel">
  <div class="jumbotron">
    <h1 class="display-4 title">
      <%= @task.title %>
      <%=link_to '🖋️ edit', edit_task_url, class: 'btn btn-primary'%>
    </h1>
    <p class="lead">
      <%= @task.details %>
    </p>
    <hr class="my-4">
    <br>
    <div class="d-flex justify-content-between p-0 completed">
      <%if @task.completed %>
        <h4 class="alert alert-success">This task is completed</h4>
      <%else%>
        <h4 class="alert alert-danger">This task is not complete</h4>
      <%end%>
    </div>
    <%=link_to 'Back to list', tasks_url, class: 'task-link'%>
  </div>
</div>